import type { Metadata } from "next";
import { Cormorant, Lato, Montserrat } from "next/font/google";

import "./globals.css";

const cormorant = Cormorant({
	variable: "--font-cormorant",
	subsets: ["latin"],
});

const lato = Lato({
	variable: "--font-lato",
	weight: "400",
	subsets: ["latin"],
});

const montserrat = Montserrat({
	variable: "--font-montserrat",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "DJ Victor Samuel",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pt-BR">
			<body
				className={`${cormorant.variable} ${lato.variable} ${montserrat.variable}`}
			>
				<main>{children}</main>
			</body>
		</html>
	);
}
